# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parser_gui_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("border: 0;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(113, 7, 198, 255), stop:1 rgba(218, 148, 255, 255));\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("QTabBar::tab\n"
"{\n"
"    background: rgb(93, 26, 179);\n"
"    margin-left: 2ex;\n"
"    min-width: 30ex;\n"
"    min-height: 15ex;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    margin-top: 2ex;\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    background: rgb(89,0,159);\n"
"}\n"
"\n"
"QTabBar\n"
"{\n"
"    background: rgba(255,255,255,0)\n"
"}\n"
"\n"
"\n"
"border: 0\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.menu = QtWidgets.QTabWidget(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(0, 10, 825, 701))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        self.menu.setFont(font)
        self.menu.setStyleSheet("border: 0;\n"
"\n"
"")
        self.menu.setTabPosition(QtWidgets.QTabWidget.North)
        self.menu.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.menu.setObjectName("menu")
        self.main_page = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(8)
        self.main_page.setFont(font)
        self.main_page.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.main_page.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.main_page.setAutoFillBackground(False)
        self.main_page.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(89, 0, 159, 255), stop:1  rgba(218, 148, 255, 255));")
        self.main_page.setObjectName("main_page")
        self.Change_capitalization_frame = QtWidgets.QFrame(self.main_page)
        self.Change_capitalization_frame.setGeometry(QtCore.QRect(445, 15, 331, 101))
        self.Change_capitalization_frame.setStyleSheet("background: rgba(255,255,255,0)")
        self.Change_capitalization_frame.setObjectName("Change_capitalization_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Change_capitalization_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Text_change_capitalization_label = QtWidgets.QLabel(self.Change_capitalization_frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.Text_change_capitalization_label.setFont(font)
        self.Text_change_capitalization_label.setStyleSheet("font-size: 16px;\n"
"color: rgb(255,255,255);\n"
"background: rgba(255,255,255,0);")
        self.Text_change_capitalization_label.setObjectName("Text_change_capitalization_label")
        self.verticalLayout_3.addWidget(self.Text_change_capitalization_label)
        self.Value_change_capitalization_label = QtWidgets.QLabel(self.Change_capitalization_frame)
        self.Value_change_capitalization_label.setStyleSheet("font-size: 16px;\n"
"color: rgb(255,0,0);\n"
"background: rgba(255,255,255,0);\n"
"font-weight: bold")
        self.Value_change_capitalization_label.setObjectName("Value_change_capitalization_label")
        self.verticalLayout_3.addWidget(self.Value_change_capitalization_label)
        self.Time_update_change_capitalization_label = QtWidgets.QLabel(self.Change_capitalization_frame)
        self.Time_update_change_capitalization_label.setStyleSheet("font-size: 16px;\n"
"color: rgb(255,255,255)")
        self.Time_update_change_capitalization_label.setObjectName("Time_update_change_capitalization_label")
        self.verticalLayout_3.addWidget(self.Time_update_change_capitalization_label)
        self.Value_volume_frame = QtWidgets.QFrame(self.main_page)
        self.Value_volume_frame.setGeometry(QtCore.QRect(40, 141, 331, 101))
        self.Value_volume_frame.setStyleSheet("background: rgba(255,255,255,0)")
        self.Value_volume_frame.setObjectName("Value_volume_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Value_volume_frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Text_volume_label = QtWidgets.QLabel(self.Value_volume_frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.Text_volume_label.setFont(font)
        self.Text_volume_label.setStyleSheet("font-size: 16px;\n"
"color: rgb(255,255,255);\n"
"background: rgba(255,255,255,0);")
        self.Text_volume_label.setObjectName("Text_volume_label")
        self.verticalLayout_7.addWidget(self.Text_volume_label)
        self.Value_volume_label = QtWidgets.QLabel(self.Value_volume_frame)
        self.Value_volume_label.setStyleSheet("font-size: 16px;\n"
"color: rgb(0,255,0);\n"
"background: rgba(255,255,255,0);\n"
"font-weight: bold")
        self.Value_volume_label.setObjectName("Value_volume_label")
        self.verticalLayout_7.addWidget(self.Value_volume_label)
        self.Time_update_volume_label = QtWidgets.QLabel(self.Value_volume_frame)
        self.Time_update_volume_label.setStyleSheet("font-size: 16px;\n"
"color: rgb(255,255,255)")
        self.Time_update_volume_label.setObjectName("Time_update_volume_label")
        self.verticalLayout_7.addWidget(self.Time_update_volume_label)
        self.Change_volume_frame = QtWidgets.QFrame(self.main_page)
        self.Change_volume_frame.setGeometry(QtCore.QRect(445, 141, 331, 101))
        self.Change_volume_frame.setStyleSheet("background: rgba(255,255,255,0)")
        self.Change_volume_frame.setObjectName("Change_volume_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Change_volume_frame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Text_information_source_label = QtWidgets.QLabel(self.Change_volume_frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.Text_information_source_label.setFont(font)
        self.Text_information_source_label.setStyleSheet("font-size: 16px;\n"
"color: rgb(255,255,255);\n"
"background: rgba(255,255,255,0);")
        self.Text_information_source_label.setObjectName("Text_information_source_label")
        self.verticalLayout_8.addWidget(self.Text_information_source_label)
        self.Value_information_source_label = QtWidgets.QLabel(self.Change_volume_frame)
        self.Value_information_source_label.setStyleSheet("font-size: 16px;\n"
"color: rgb(51,153,255);\n"
"background: rgba(255,255,255,0);\n"
"font-weight: bold")
        self.Value_information_source_label.setObjectName("Value_information_source_label")
        self.verticalLayout_8.addWidget(self.Value_information_source_label)
        self.Main_frame = QtWidgets.QFrame(self.main_page)
        self.Main_frame.setGeometry(QtCore.QRect(10, 10, 801, 241))
        self.Main_frame.setStyleSheet("background: rgba(255,255,255,0)")
        self.Main_frame.setObjectName("Main_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Main_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Capitalization_frame = QtWidgets.QFrame(self.Main_frame)
        self.Capitalization_frame.setStyleSheet("background-color: rgb(255,255,255,0);")
        self.Capitalization_frame.setObjectName("Capitalization_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Capitalization_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Change_capitalization_label = QtWidgets.QLabel(self.Capitalization_frame)
        self.Change_capitalization_label.setStyleSheet("background-color: rgb(255,255,255,30);\n"
"border-radius: 10px\n"
"")
        self.Change_capitalization_label.setText("")
        self.Change_capitalization_label.setObjectName("Change_capitalization_label")
        self.horizontalLayout.addWidget(self.Change_capitalization_label)
        self.Capitalization_label = QtWidgets.QLabel(self.Capitalization_frame)
        self.Capitalization_label.setStyleSheet("background-color: rgb(255,255,255,30);\n"
"border-radius: 10px\n"
"")
        self.Capitalization_label.setText("")
        self.Capitalization_label.setObjectName("Capitalization_label")
        self.horizontalLayout.addWidget(self.Capitalization_label)
        self.verticalLayout_4.addWidget(self.Capitalization_frame)
        self.Volume_frame = QtWidgets.QFrame(self.Main_frame)
        self.Volume_frame.setStyleSheet("background-color: rgb(255,255,255,0);")
        self.Volume_frame.setObjectName("Volume_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Volume_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Change_volume_label = QtWidgets.QLabel(self.Volume_frame)
        self.Change_volume_label.setStyleSheet("background-color: rgb(255,255,255,30);\n"
"border-radius: 10px\n"
"")
        self.Change_volume_label.setText("")
        self.Change_volume_label.setObjectName("Change_volume_label")
        self.horizontalLayout_6.addWidget(self.Change_volume_label)
        self.Volume_label = QtWidgets.QLabel(self.Volume_frame)
        self.Volume_label.setStyleSheet("background-color: rgb(255,255,255,30);\n"
"border-radius: 10px\n"
"")
        self.Volume_label.setText("")
        self.Volume_label.setObjectName("Volume_label")
        self.horizontalLayout_6.addWidget(self.Volume_label)
        self.verticalLayout_4.addWidget(self.Volume_frame)
        self.Value_capitalization_frame = QtWidgets.QFrame(self.main_page)
        self.Value_capitalization_frame.setGeometry(QtCore.QRect(40, 15, 331, 101))
        self.Value_capitalization_frame.setStyleSheet("background: rgba(255,255,255,0)")
        self.Value_capitalization_frame.setObjectName("Value_capitalization_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Value_capitalization_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Text_capitalization_label = QtWidgets.QLabel(self.Value_capitalization_frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.Text_capitalization_label.setFont(font)
        self.Text_capitalization_label.setStyleSheet("font-size: 16px;\n"
"color: rgb(255,255,255);\n"
"background: rgba(255,255,255,0);")
        self.Text_capitalization_label.setObjectName("Text_capitalization_label")
        self.verticalLayout.addWidget(self.Text_capitalization_label)
        self.Value_capitalization_label = QtWidgets.QLabel(self.Value_capitalization_frame)
        self.Value_capitalization_label.setStyleSheet("font-size: 16px;\n"
"color: rgb(0,255,0);\n"
"background: rgba(255,255,255,0);\n"
"font-weight: bold")
        self.Value_capitalization_label.setObjectName("Value_capitalization_label")
        self.verticalLayout.addWidget(self.Value_capitalization_label)
        self.Time_update_capitalization_label = QtWidgets.QLabel(self.Value_capitalization_frame)
        self.Time_update_capitalization_label.setStyleSheet("font-size: 16px;\n"
"color: rgb(255,255,255)")
        self.Time_update_capitalization_label.setObjectName("Time_update_capitalization_label")
        self.verticalLayout.addWidget(self.Time_update_capitalization_label)
        self.Update_Button = QtWidgets.QToolButton(self.main_page)
        self.Update_Button.setGeometry(QtCore.QRect(10, 260, 801, 31))
        self.Update_Button.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 15px;")
        self.Update_Button.setObjectName("Update_Button")
        self.Telegram_Icon_Button = QtWidgets.QPushButton(self.main_page)
        self.Telegram_Icon_Button.setGeometry(QtCore.QRect(20, 394, 40, 40))
        self.Telegram_Icon_Button.setStyleSheet("background: rgba(255,255,255,0);\n"
"text-align: end;")
        self.Telegram_Icon_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icons8-телеграм-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Telegram_Icon_Button.setIcon(icon)
        self.Telegram_Icon_Button.setIconSize(QtCore.QSize(40, 40))
        self.Telegram_Icon_Button.setObjectName("Telegram_Icon_Button")
        self.Telegram_text_Button = QtWidgets.QPushButton(self.main_page)
        self.Telegram_text_Button.setGeometry(QtCore.QRect(70, 399, 321, 31))
        self.Telegram_text_Button.setStyleSheet("font-size: 16px;\n"
"color: rgb(255,255,255);\n"
"background: rgba(255,255,255,0)")
        self.Telegram_text_Button.setObjectName("Telegram_text_Button")
        self.Direction_change_capitalization_Icon_Button = QtWidgets.QPushButton(self.main_page)
        self.Direction_change_capitalization_Icon_Button.setGeometry(QtCore.QRect(620, 45, 51, 41))
        self.Direction_change_capitalization_Icon_Button.setStyleSheet("background: rgba(255,255,255,0)")
        self.Direction_change_capitalization_Icon_Button.setText("")
        self.Direction_change_capitalization_Icon_Button.setObjectName("Direction_change_capitalization_Icon_Button")
        self.Coin_Icon_Button = QtWidgets.QPushButton(self.main_page)
        self.Coin_Icon_Button.setGeometry(QtCore.QRect(20, 519, 40, 40))
        self.Coin_Icon_Button.setStyleSheet("background: rgba(255,255,255,0);\n"
"text-align: end;")
        self.Coin_Icon_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/coin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Coin_Icon_Button.setIcon(icon1)
        self.Coin_Icon_Button.setIconSize(QtCore.QSize(40, 40))
        self.Coin_Icon_Button.setObjectName("Coin_Icon_Button")
        self.Coin_text_Button = QtWidgets.QPushButton(self.main_page)
        self.Coin_text_Button.setGeometry(QtCore.QRect(70, 524, 271, 31))
        self.Coin_text_Button.setStyleSheet("font-size: 16px;\n"
"color: rgb(255,249,61);\n"
"background: rgba(255,255,255,0)")
        self.Coin_text_Button.setObjectName("Coin_text_Button")
        self.Switch_to_telegram_bot_Button = QtWidgets.QPushButton(self.main_page)
        self.Switch_to_telegram_bot_Button.setGeometry(QtCore.QRect(14, 384, 381, 60))
        self.Switch_to_telegram_bot_Button.setStyleSheet("background-color: rgb(255,255,255,50);\n"
"border-radius: 18px")
        self.Switch_to_telegram_bot_Button.setText("")
        self.Switch_to_telegram_bot_Button.setObjectName("Switch_to_telegram_bot_Button")
        self.Switch_to_support_the_autor_Button = QtWidgets.QPushButton(self.main_page)
        self.Switch_to_support_the_autor_Button.setGeometry(QtCore.QRect(14, 509, 381, 60))
        self.Switch_to_support_the_autor_Button.setStyleSheet("background-color: rgb(255,255,255,50);\n"
"border-radius: 18px")
        self.Switch_to_support_the_autor_Button.setText("")
        self.Switch_to_support_the_autor_Button.setObjectName("Switch_to_support_the_autor_Button")
        self.Footer_label = QtWidgets.QLabel(self.main_page)
        self.Footer_label.setGeometry(QtCore.QRect(0, 370, 825, 471))
        self.Footer_label.setText("")
        self.Footer_label.setObjectName("Footer_label")
        self.Description_telegram_bot_label = QtWidgets.QLabel(self.main_page)
        self.Description_telegram_bot_label.setGeometry(QtCore.QRect(450, 384, 331, 95))
        self.Description_telegram_bot_label.setStyleSheet("background: rgba(255,255,255,0);\n"
"color: rgb(255,255,255);\n"
"font-size: 16px")
        self.Description_telegram_bot_label.setObjectName("Description_telegram_bot_label")
        self.Description_support_the_autor_label = QtWidgets.QLabel(self.main_page)
        self.Description_support_the_autor_label.setGeometry(QtCore.QRect(450, 509, 331, 95))
        self.Description_support_the_autor_label.setStyleSheet("background: rgba(255,255,255,0);\n"
"color: rgb(255,255,255);\n"
"font-size: 16px")
        self.Description_support_the_autor_label.setObjectName("Description_support_the_autor_label")
        self.Footer_label.raise_()
        self.Main_frame.raise_()
        self.Value_capitalization_frame.raise_()
        self.Change_capitalization_frame.raise_()
        self.Value_volume_frame.raise_()
        self.Change_volume_frame.raise_()
        self.Update_Button.raise_()
        self.Telegram_Icon_Button.raise_()
        self.Telegram_text_Button.raise_()
        self.Direction_change_capitalization_Icon_Button.raise_()
        self.Coin_Icon_Button.raise_()
        self.Coin_text_Button.raise_()
        self.Switch_to_telegram_bot_Button.raise_()
        self.Switch_to_support_the_autor_Button.raise_()
        self.Description_telegram_bot_label.raise_()
        self.Description_support_the_autor_label.raise_()
        self.menu.addTab(self.main_page, "")
        self.item_page = QtWidgets.QWidget()
        self.item_page.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(89, 0, 159, 255), stop:1  rgba(218, 148, 255, 255));")
        self.item_page.setObjectName("item_page")
        self.menu.addTab(self.item_page, "")
        self.additional_page = QtWidgets.QWidget()
        self.additional_page.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(89, 0, 159, 255), stop:1  rgba(218, 148, 255, 255));\n"
"")
        self.additional_page.setObjectName("additional_page")
        self.Popular_text_label = QtWidgets.QLabel(self.additional_page)
        self.Popular_text_label.setGeometry(QtCore.QRect(257, 10, 311, 30))
        self.Popular_text_label.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 24px;\n"
"background: rgba(255,255,255,0);")
        self.Popular_text_label.setObjectName("Popular_text_label")
        self.Max_growth_text_label = QtWidgets.QLabel(self.additional_page)
        self.Max_growth_text_label.setGeometry(QtCore.QRect(202, 325, 421, 30))
        self.Max_growth_text_label.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 24px;\n"
"background: rgba(255,255,255,0);")
        self.Max_growth_text_label.setObjectName("Max_growth_text_label")
        self.Popular_Icon_Button_1 = QtWidgets.QPushButton(self.additional_page)
        self.Popular_Icon_Button_1.setGeometry(QtCore.QRect(700, 126, 40, 40))
        self.Popular_Icon_Button_1.setStyleSheet("background: rgb(255,255,255,0)")
        self.Popular_Icon_Button_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/trending_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Popular_Icon_Button_1.setIcon(icon2)
        self.Popular_Icon_Button_1.setIconSize(QtCore.QSize(40, 40))
        self.Popular_Icon_Button_1.setObjectName("Popular_Icon_Button_1")
        self.Popular_Icon_Button_2 = QtWidgets.QPushButton(self.additional_page)
        self.Popular_Icon_Button_2.setGeometry(QtCore.QRect(700, 194, 40, 40))
        self.Popular_Icon_Button_2.setStyleSheet("background: rgb(255,255,255,0)")
        self.Popular_Icon_Button_2.setText("")
        self.Popular_Icon_Button_2.setIcon(icon2)
        self.Popular_Icon_Button_2.setIconSize(QtCore.QSize(40, 40))
        self.Popular_Icon_Button_2.setObjectName("Popular_Icon_Button_2")
        self.Popular_Icon_Button_3 = QtWidgets.QPushButton(self.additional_page)
        self.Popular_Icon_Button_3.setGeometry(QtCore.QRect(700, 260, 40, 40))
        self.Popular_Icon_Button_3.setStyleSheet("background: rgb(255,255,255,0)")
        self.Popular_Icon_Button_3.setText("")
        self.Popular_Icon_Button_3.setIcon(icon2)
        self.Popular_Icon_Button_3.setIconSize(QtCore.QSize(40, 40))
        self.Popular_Icon_Button_3.setObjectName("Popular_Icon_Button_3")
        self.Main_max_growth_crypto_Frame = QtWidgets.QFrame(self.additional_page)
        self.Main_max_growth_crypto_Frame.setGeometry(QtCore.QRect(20, 365, 781, 261))
        self.Main_max_growth_crypto_Frame.setStyleSheet("background: rgba(255,255,255, 50);\n"
"border-radius: 15px;")
        self.Main_max_growth_crypto_Frame.setObjectName("Main_max_growth_crypto_Frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Main_max_growth_crypto_Frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Max_growth_column_horizontal_Layout = QtWidgets.QHBoxLayout()
        self.Max_growth_column_horizontal_Layout.setObjectName("Max_growth_column_horizontal_Layout")
        self.Max_growth_column_name_label = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_column_name_label.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(79, 79, 79);\n"
"")
        self.Max_growth_column_name_label.setObjectName("Max_growth_column_name_label")
        self.Max_growth_column_horizontal_Layout.addWidget(self.Max_growth_column_name_label)
        self.Max_growth_column_time_label = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_column_time_label.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(79, 79, 79);\n"
"")
        self.Max_growth_column_time_label.setObjectName("Max_growth_column_time_label")
        self.Max_growth_column_horizontal_Layout.addWidget(self.Max_growth_column_time_label)
        self.Max_growth_column_cost_label = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_column_cost_label.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(79, 79, 79);")
        self.Max_growth_column_cost_label.setObjectName("Max_growth_column_cost_label")
        self.Max_growth_column_horizontal_Layout.addWidget(self.Max_growth_column_cost_label)
        self.Max_growth_column_change_label = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_column_change_label.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(79, 79, 79);")
        self.Max_growth_column_change_label.setObjectName("Max_growth_column_change_label")
        self.Max_growth_column_horizontal_Layout.addWidget(self.Max_growth_column_change_label)
        self.verticalLayout_5.addLayout(self.Max_growth_column_horizontal_Layout)
        self.Max_growth_horizontal_Layout_1 = QtWidgets.QHBoxLayout()
        self.Max_growth_horizontal_Layout_1.setObjectName("Max_growth_horizontal_Layout_1")
        self.Max_growth_name_label_1 = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_name_label_1.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Max_growth_name_label_1.setObjectName("Max_growth_name_label_1")
        self.Max_growth_horizontal_Layout_1.addWidget(self.Max_growth_name_label_1)
        self.Max_growth_time_label_1 = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_time_label_1.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(157, 0, 255);")
        self.Max_growth_time_label_1.setObjectName("Max_growth_time_label_1")
        self.Max_growth_horizontal_Layout_1.addWidget(self.Max_growth_time_label_1)
        self.Max_growth_cost_label_1 = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_cost_label_1.setStyleSheet("color: rgb(0,255,0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Max_growth_cost_label_1.setObjectName("Max_growth_cost_label_1")
        self.Max_growth_horizontal_Layout_1.addWidget(self.Max_growth_cost_label_1)
        self.Max_growth_change_label_1 = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_change_label_1.setStyleSheet("color: rgb(0,255,0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Max_growth_change_label_1.setObjectName("Max_growth_change_label_1")
        self.Max_growth_horizontal_Layout_1.addWidget(self.Max_growth_change_label_1)
        self.verticalLayout_5.addLayout(self.Max_growth_horizontal_Layout_1)
        self.Max_growth_horizontal_Layout_2 = QtWidgets.QHBoxLayout()
        self.Max_growth_horizontal_Layout_2.setObjectName("Max_growth_horizontal_Layout_2")
        self.Max_growth_name_label_2 = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_name_label_2.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Max_growth_name_label_2.setObjectName("Max_growth_name_label_2")
        self.Max_growth_horizontal_Layout_2.addWidget(self.Max_growth_name_label_2)
        self.Max_growth_time_label_2 = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_time_label_2.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(157, 0, 255);")
        self.Max_growth_time_label_2.setObjectName("Max_growth_time_label_2")
        self.Max_growth_horizontal_Layout_2.addWidget(self.Max_growth_time_label_2)
        self.Max_growth_cost_label_2 = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_cost_label_2.setStyleSheet("color: rgb(0,255,0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Max_growth_cost_label_2.setObjectName("Max_growth_cost_label_2")
        self.Max_growth_horizontal_Layout_2.addWidget(self.Max_growth_cost_label_2)
        self.Max_growth_change_label_2 = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_change_label_2.setStyleSheet("color: rgb(0,255,0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Max_growth_change_label_2.setObjectName("Max_growth_change_label_2")
        self.Max_growth_horizontal_Layout_2.addWidget(self.Max_growth_change_label_2)
        self.verticalLayout_5.addLayout(self.Max_growth_horizontal_Layout_2)
        self.Max_growth_horizontal_Layout_3 = QtWidgets.QHBoxLayout()
        self.Max_growth_horizontal_Layout_3.setObjectName("Max_growth_horizontal_Layout_3")
        self.Max_growth_name_label_3 = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_name_label_3.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Max_growth_name_label_3.setObjectName("Max_growth_name_label_3")
        self.Max_growth_horizontal_Layout_3.addWidget(self.Max_growth_name_label_3)
        self.Max_growth_time_label_3 = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_time_label_3.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(157, 0, 255);")
        self.Max_growth_time_label_3.setObjectName("Max_growth_time_label_3")
        self.Max_growth_horizontal_Layout_3.addWidget(self.Max_growth_time_label_3)
        self.Max_growth_cost_label_3 = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_cost_label_3.setStyleSheet("color: rgb(0,255,0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Max_growth_cost_label_3.setObjectName("Max_growth_cost_label_3")
        self.Max_growth_horizontal_Layout_3.addWidget(self.Max_growth_cost_label_3)
        self.Max_growth_change_label_3 = QtWidgets.QLabel(self.Main_max_growth_crypto_Frame)
        self.Max_growth_change_label_3.setStyleSheet("color: rgb(0,255,0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Max_growth_change_label_3.setObjectName("Max_growth_change_label_3")
        self.Max_growth_horizontal_Layout_3.addWidget(self.Max_growth_change_label_3)
        self.verticalLayout_5.addLayout(self.Max_growth_horizontal_Layout_3)
        self.Max_growth_Icon_Button_1 = QtWidgets.QPushButton(self.additional_page)
        self.Max_growth_Icon_Button_1.setGeometry(QtCore.QRect(700, 444, 40, 40))
        self.Max_growth_Icon_Button_1.setStyleSheet("background: rgb(255,255,255,0)")
        self.Max_growth_Icon_Button_1.setText("")
        self.Max_growth_Icon_Button_1.setIcon(icon2)
        self.Max_growth_Icon_Button_1.setIconSize(QtCore.QSize(40, 40))
        self.Max_growth_Icon_Button_1.setObjectName("Max_growth_Icon_Button_1")
        self.Max_growth_Icon_Button_2 = QtWidgets.QPushButton(self.additional_page)
        self.Max_growth_Icon_Button_2.setGeometry(QtCore.QRect(700, 508, 40, 40))
        self.Max_growth_Icon_Button_2.setStyleSheet("background: rgb(255,255,255,0)")
        self.Max_growth_Icon_Button_2.setText("")
        self.Max_growth_Icon_Button_2.setIcon(icon2)
        self.Max_growth_Icon_Button_2.setIconSize(QtCore.QSize(40, 40))
        self.Max_growth_Icon_Button_2.setObjectName("Max_growth_Icon_Button_2")
        self.Max_growth_Icon_Button_3 = QtWidgets.QPushButton(self.additional_page)
        self.Max_growth_Icon_Button_3.setGeometry(QtCore.QRect(700, 569, 40, 40))
        self.Max_growth_Icon_Button_3.setStyleSheet("background: rgb(255,255,255,0)")
        self.Max_growth_Icon_Button_3.setText("")
        self.Max_growth_Icon_Button_3.setIcon(icon2)
        self.Max_growth_Icon_Button_3.setIconSize(QtCore.QSize(40, 40))
        self.Max_growth_Icon_Button_3.setObjectName("Max_growth_Icon_Button_3")
        self.Main_popular_crypto_Frame = QtWidgets.QFrame(self.additional_page)
        self.Main_popular_crypto_Frame.setGeometry(QtCore.QRect(20, 50, 781, 261))
        self.Main_popular_crypto_Frame.setStyleSheet("background: rgba(255,255,255, 50);\n"
"border-radius: 15px;")
        self.Main_popular_crypto_Frame.setObjectName("Main_popular_crypto_Frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Main_popular_crypto_Frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Popular_column_horizontalLayout = QtWidgets.QHBoxLayout()
        self.Popular_column_horizontalLayout.setObjectName("Popular_column_horizontalLayout")
        self.Popular_column_name_label = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_column_name_label.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(79, 79, 79);\n"
"")
        self.Popular_column_name_label.setObjectName("Popular_column_name_label")
        self.Popular_column_horizontalLayout.addWidget(self.Popular_column_name_label)
        self.Popular_column_time_label = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_column_time_label.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(79, 79, 79);\n"
"")
        self.Popular_column_time_label.setObjectName("Popular_column_time_label")
        self.Popular_column_horizontalLayout.addWidget(self.Popular_column_time_label)
        self.Popular_column_cost_label = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_column_cost_label.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(79, 79, 79);")
        self.Popular_column_cost_label.setObjectName("Popular_column_cost_label")
        self.Popular_column_horizontalLayout.addWidget(self.Popular_column_cost_label)
        self.Popular_column_change_label = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_column_change_label.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(79, 79, 79);")
        self.Popular_column_change_label.setObjectName("Popular_column_change_label")
        self.Popular_column_horizontalLayout.addWidget(self.Popular_column_change_label)
        self.verticalLayout_2.addLayout(self.Popular_column_horizontalLayout)
        self.Popular_horizontal_Layout_1 = QtWidgets.QHBoxLayout()
        self.Popular_horizontal_Layout_1.setObjectName("Popular_horizontal_Layout_1")
        self.Popular_name_label_1 = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_name_label_1.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Popular_name_label_1.setObjectName("Popular_name_label_1")
        self.Popular_horizontal_Layout_1.addWidget(self.Popular_name_label_1)
        self.Popular_time_label_1 = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_time_label_1.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(157, 0, 255);")
        self.Popular_time_label_1.setObjectName("Popular_time_label_1")
        self.Popular_horizontal_Layout_1.addWidget(self.Popular_time_label_1)
        self.Popular_cost_label_1 = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_cost_label_1.setStyleSheet("color: rgb(0,255,0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Popular_cost_label_1.setObjectName("Popular_cost_label_1")
        self.Popular_horizontal_Layout_1.addWidget(self.Popular_cost_label_1)
        self.Popular_change_label_1 = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_change_label_1.setStyleSheet("color: rgb(0,255,0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Popular_change_label_1.setObjectName("Popular_change_label_1")
        self.Popular_horizontal_Layout_1.addWidget(self.Popular_change_label_1)
        self.verticalLayout_2.addLayout(self.Popular_horizontal_Layout_1)
        self.Popular_horizontal_Layout_2 = QtWidgets.QHBoxLayout()
        self.Popular_horizontal_Layout_2.setObjectName("Popular_horizontal_Layout_2")
        self.Popular_name_label_2 = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_name_label_2.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Popular_name_label_2.setObjectName("Popular_name_label_2")
        self.Popular_horizontal_Layout_2.addWidget(self.Popular_name_label_2)
        self.Popular_time_label_2 = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_time_label_2.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(157, 0, 255);")
        self.Popular_time_label_2.setObjectName("Popular_time_label_2")
        self.Popular_horizontal_Layout_2.addWidget(self.Popular_time_label_2)
        self.Popular_cost_label_2 = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_cost_label_2.setStyleSheet("color: rgb(0,255,0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Popular_cost_label_2.setObjectName("Popular_cost_label_2")
        self.Popular_horizontal_Layout_2.addWidget(self.Popular_cost_label_2)
        self.Popular_change_label_2 = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_change_label_2.setStyleSheet("color: rgb(0,255,0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Popular_change_label_2.setObjectName("Popular_change_label_2")
        self.Popular_horizontal_Layout_2.addWidget(self.Popular_change_label_2)
        self.verticalLayout_2.addLayout(self.Popular_horizontal_Layout_2)
        self.Popular_horizontal_Layout_3 = QtWidgets.QHBoxLayout()
        self.Popular_horizontal_Layout_3.setObjectName("Popular_horizontal_Layout_3")
        self.Popular_name_label_3 = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_name_label_3.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Popular_name_label_3.setObjectName("Popular_name_label_3")
        self.Popular_horizontal_Layout_3.addWidget(self.Popular_name_label_3)
        self.Popular_time_label_3 = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_time_label_3.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16px;\n"
"background-color: rgb(157, 0, 255);")
        self.Popular_time_label_3.setObjectName("Popular_time_label_3")
        self.Popular_horizontal_Layout_3.addWidget(self.Popular_time_label_3)
        self.Popular_cost_label_3 = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_cost_label_3.setStyleSheet("color: rgb(0,255,0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Popular_cost_label_3.setObjectName("Popular_cost_label_3")
        self.Popular_horizontal_Layout_3.addWidget(self.Popular_cost_label_3)
        self.Popular_change_label_3 = QtWidgets.QLabel(self.Main_popular_crypto_Frame)
        self.Popular_change_label_3.setStyleSheet("color: rgb(0,255,0);\n"
"font-size: 16px;\n"
"font-weight: bold;\n"
"background-color: rgb(157, 0, 255);")
        self.Popular_change_label_3.setObjectName("Popular_change_label_3")
        self.Popular_horizontal_Layout_3.addWidget(self.Popular_change_label_3)
        self.verticalLayout_2.addLayout(self.Popular_horizontal_Layout_3)
        self.Popular_text_label.raise_()
        self.Max_growth_text_label.raise_()
        self.Popular_column_change_label.raise_()
        self.Popular_column_cost_label.raise_()
        self.Popular_column_time_label.raise_()
        self.Popular_column_name_label.raise_()
        self.Main_max_growth_crypto_Frame.raise_()
        self.Popular_Icon_Button_1.raise_()
        self.Popular_Icon_Button_2.raise_()
        self.Popular_Icon_Button_3.raise_()
        self.Max_growth_Icon_Button_1.raise_()
        self.Max_growth_Icon_Button_2.raise_()
        self.Max_growth_Icon_Button_3.raise_()
        self.menu.addTab(self.additional_page, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.menu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Text_change_capitalization_label.setText(_translate("MainWindow", "Изменение за последние сутки:"))
        self.Value_change_capitalization_label.setText(_translate("MainWindow", "Снизилась на 1.4%"))
        self.Time_update_change_capitalization_label.setText(_translate("MainWindow", "Обновлено в 12:13:14"))
        self.Text_volume_label.setText(_translate("MainWindow", "Общий объём торгов:"))
        self.Value_volume_label.setText(_translate("MainWindow", "$ 234 234 234"))
        self.Time_update_volume_label.setText(_translate("MainWindow", "Обновлено в 12:13:14"))
        self.Text_information_source_label.setText(_translate("MainWindow", "Информация с сайта:"))
        self.Value_information_source_label.setText(_translate("MainWindow", "\"coingecko.com\""))
        self.Text_capitalization_label.setText(_translate("MainWindow", "Рыночная капитализация криптовалюты:"))
        self.Value_capitalization_label.setText(_translate("MainWindow", "$ 2 234 234 234 234"))
        self.Time_update_capitalization_label.setText(_translate("MainWindow", "Обновлено в 12:13:14"))
        self.Update_Button.setText(_translate("MainWindow", "Нажмите, чтобы обновить"))
        self.Telegram_text_Button.setText(_translate("MainWindow", "Нажмите, чтобы перейти в телеграм-бота"))
        self.Coin_text_Button.setText(_translate("MainWindow", "Нажмите,чтобы поддержать автора"))
        self.Description_telegram_bot_label.setText(_translate("MainWindow", "Преимущества телеграм-бота,\n"
"по сравнению с приложением:\n"
"1. Сигналы от торгового бота\n"
"2. Отслеживание выбранной криптовалюты\n"
"3. Демо-счёт для обучения торговле"))
        self.Description_support_the_autor_label.setText(_translate("MainWindow", "Преимущества телеграм-бота,\n"
"по сравнению с приложением:\n"
"1. Сигналы от торгового бота\n"
"2. Отслеживание выбранной криптовалюты\n"
"3. Демо-счёт для обучения торговле"))
        self.menu.setTabText(self.menu.indexOf(self.main_page), _translate("MainWindow", "Main"))
        self.menu.setTabText(self.menu.indexOf(self.item_page), _translate("MainWindow", "Item"))
        self.Popular_text_label.setText(_translate("MainWindow", "Популярные криптовалюты"))
        self.Max_growth_text_label.setText(_translate("MainWindow", "Криптовалюты с наибольшим ростом"))
        self.Max_growth_column_name_label.setText(_translate("MainWindow", "            Название\n"
"        криптовалюты"))
        self.Max_growth_column_time_label.setText(_translate("MainWindow", "           Обновлено\n"
"             (время)"))
        self.Max_growth_column_cost_label.setText(_translate("MainWindow", "          Стоимость"))
        self.Max_growth_column_change_label.setText(_translate("MainWindow", "   Изменение стоимости\n"
"           за 24 часа"))
        self.Max_growth_name_label_1.setText(_translate("MainWindow", "             bitcoin"))
        self.Max_growth_time_label_1.setText(_translate("MainWindow", "            12:13:14"))
        self.Max_growth_cost_label_1.setText(_translate("MainWindow", "           $ 70 000"))
        self.Max_growth_change_label_1.setText(_translate("MainWindow", "        6%"))
        self.Max_growth_name_label_2.setText(_translate("MainWindow", "             bitcoin"))
        self.Max_growth_time_label_2.setText(_translate("MainWindow", "            12:13:14"))
        self.Max_growth_cost_label_2.setText(_translate("MainWindow", "           $ 70 000"))
        self.Max_growth_change_label_2.setText(_translate("MainWindow", "        6%"))
        self.Max_growth_name_label_3.setText(_translate("MainWindow", "             bitcoin"))
        self.Max_growth_time_label_3.setText(_translate("MainWindow", "            12:13:14"))
        self.Max_growth_cost_label_3.setText(_translate("MainWindow", "           $ 70 000"))
        self.Max_growth_change_label_3.setText(_translate("MainWindow", "        6%"))
        self.Popular_column_name_label.setText(_translate("MainWindow", "            Название\n"
"        криптовалюты"))
        self.Popular_column_time_label.setText(_translate("MainWindow", "           Обновлено\n"
"             (время)"))
        self.Popular_column_cost_label.setText(_translate("MainWindow", "          Стоимость"))
        self.Popular_column_change_label.setText(_translate("MainWindow", "   Изменение стоимости\n"
"           за 24 часа"))
        self.Popular_name_label_1.setText(_translate("MainWindow", "             bitcoin"))
        self.Popular_time_label_1.setText(_translate("MainWindow", "            12:13:14"))
        self.Popular_cost_label_1.setText(_translate("MainWindow", "           $ 70 000"))
        self.Popular_change_label_1.setText(_translate("MainWindow", "        6%"))
        self.Popular_name_label_2.setText(_translate("MainWindow", "             bitcoin"))
        self.Popular_time_label_2.setText(_translate("MainWindow", "            12:13:14"))
        self.Popular_cost_label_2.setText(_translate("MainWindow", "           $ 70 000"))
        self.Popular_change_label_2.setText(_translate("MainWindow", "        6%"))
        self.Popular_name_label_3.setText(_translate("MainWindow", "             bitcoin"))
        self.Popular_time_label_3.setText(_translate("MainWindow", "            12:13:14"))
        self.Popular_cost_label_3.setText(_translate("MainWindow", "           $ 70 000"))
        self.Popular_change_label_3.setText(_translate("MainWindow", "        6%"))
        self.menu.setTabText(self.menu.indexOf(self.additional_page), _translate("MainWindow", "Additional"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
